import rectangle from '../../assets/Rectangle 5.png'
import './detailsSection.css'
function DetailSection() {
  return (
    <div className='main-con'>
      <div className="container">
        <div className="row detailSectionRow p-3">
            <div className="col-lg-6 col-md-6 col-12 d-flex justify-content-center align-items-center">
                <p className='fs-5'>
                Construction projects often involve thousands of drawings and documents generated by a variety of parties. Trying to capture every piece of information into the project inevitably leads to scope gaps and miscoordination.Eliminate your headaches and allow Planscan to sort and categorize your projects information into manageable pieces.
                </p>
            </div>
            <div className="col-lg-6 col-md-6 col-12">
                <img src={rectangle} className='rectangleImg' alt="" />
            </div>
        </div>
      </div>
    </div>
  )
}

export default DetailSection
